---
- name: Builder preparing
  hosts: builder
  become: true

  tasks:
    - name: Ensure docker.io package is present
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Ensure docker.service is running
      service:
        name: docker.service
        state: started

    - name: Ensuer user ubuntu in group docker
      user:
        name: ubuntu
        groups: docker
        append: true

- name: Webserver preparing
  hosts: webserver
  become: true

  tasks:
    - name: Ensure docker.io package is present
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Ensure docker.service is running
      service:
        name: docker.service
        state: started

    - name: Ensuer user ubuntu in group docker
      user:
        name: ubuntu
        groups: docker
        append: true
